const product = [
    {
      name: "Hydrogen",
      symbol: "H",
      groupNumber: "1",
      atomicNumber: "1",
      atomicMass: "1.008",
      groupName: "Nonmetals",
      protons: "1",
      electrons: "1",
      neutrons: "0",
      valenceElectrons: "1",
      oxidationNumber: "1",
      color: "Nonmetals",
    },
    {
      name: "Helium",
      symbol: "He",
      groupNumber: "18",
      atomicNumber: "2",
      atomicMass: "4.0026",
      groupName: "Noble Gases",
      protons: "2",
      electrons: "2",
      neutrons: "2",
      valenceElectrons: "2",
      oxidationNumber: "0",
      color: "Noble_Gases",
    },
    {
      name: "Lithium",
      symbol: "Li",
      groupNumber: "1",
      atomicNumber: "3",
      atomicMass: "6.94",
      groupName: "Alkali Metals",
      protons: "3",
      electrons: "3",
      neutrons: "4",
      valenceElectrons: "1",
      oxidationNumber: "1",
      color: "Alkali_Metals",
    },
    {
      name: "Beryllium",
      symbol: "Be",
      groupNumber: "2",
      atomicNumber: "4",
      atomicMass: "9.0122",
      groupName: "Alkaline Earth Metals",
      protons: "4",
      electrons: "4",
      neutrons: "5",
      valenceElectrons: "2",
      oxidationNumber: "2",
      color: "Alkaline_Earth_Metals",
    },
    {
      name: "Boron",
      symbol: "B",
      groupNumber: "13",
      atomicNumber: "5",
      atomicMass: "10.81",
      groupName: "Metalloids",
      protons: "5",
      electrons: "5",
      neutrons: "6",
      valenceElectrons: "3",
      oxidationNumber: "3",
      color: "Metalloids",
    },
    {
      name: "Carbon",
      symbol: "C",
      groupNumber: "14",
      atomicNumber: "6",
      atomicMass: "12.011",
      groupName: "Nonmetals",
      protons: "6",
      electrons: "6",
      neutrons: "6",
      valenceElectrons: "4",
      oxidationNumber: "4",
      color: "Nonmetals",
    },
    {
      name: "Nitrogen",
      symbol: "N",
      groupNumber: "15",
      atomicNumber: "7",
      atomicMass: "14.007",
      groupName: "Nonmetals",
      protons: "7",
      electrons: "7",
      neutrons: "7",
      valenceElectrons: "5",
      oxidationNumber: "-3",
      color: "Nonmetals",
    },
    {
      name: "Oxygen",
      symbol: "O",
      groupNumber: "16",
      atomicNumber: "8",
      atomicMass: "15.999",
      groupName: "Nonmetals",
      protons: "8",
      electrons: "8",
      neutrons: "8",
      valenceElectrons: "6",
      oxidationNumber: "-2",
      color: "Nonmetals",
    },
    {
      name: "Fluorine",
      symbol: "F",
      groupNumber: "17",
      atomicNumber: "9",
      atomicMass: "18.998",
      groupName: "Halogens",
      protons: "9",
      electrons: "9",
      neutrons: "10",
      valenceElectrons: "7",
      oxidationNumber: "-1",
      color: "Halogens",
    },
    {
      name: "Neon",
      symbol: "Ne",
      groupNumber: "18",
      atomicNumber: "10",
      atomicMass: "20.180",
      groupName: "Noble Gases",
      protons: "10",
      electrons: "10",
      neutrons: "10",
      valenceElectrons: "8",
      oxidationNumber: "0",
      color: "Noble_Gases",
    },
    {
      name: "Sodium",
      symbol: "Na",
      groupNumber: "1",
      atomicNumber: "11",
      atomicMass: "22.990",
      groupName: "Alkali Metals",
      protons: "11",
      electrons: "11",
      neutrons: "12",
      valenceElectrons: "1",
      oxidationNumber: "1",
      color: "Alkali_Metals",
    },
    {
      name: "Magnesium",
      symbol: "Mg",
      groupNumber: "2",
      atomicNumber: "12",
      atomicMass: "24.305",
      groupName: "Alkaline Earth Metals",
      protons: "12",
      electrons: "12",
      neutrons: "12",
      valenceElectrons: "2",
      oxidationNumber: "2",
      color: "Alkaline_Earth_Metals",
    },
    {
      name: "Aluminum",
      symbol: "Al",
      groupNumber: "13",
      atomicNumber: "13",
      atomicMass: "26.982",
      groupName: "Other Metals",
      protons: "13",
      electrons: "13",
      neutrons: "14",
      valenceElectrons: "3",
      oxidationNumber: "3",
      color: "Other_Metals",
    },
    {
      name: "Silicon",
      symbol: "Si",
      groupNumber: "14",
      atomicNumber: "14",
      atomicMass: "28.085",
      groupName: "Metalloids",
      protons: "14",
      electrons: "14",
      neutrons: "14",
      valenceElectrons: "4",
      oxidationNumber: "4",
      color: "Metalloids",
    },
    {
      name: "Phosphorus",
      symbol: "P",
      groupNumber: "15",
      atomicNumber: "15",
      atomicMass: "30.974",
      groupName: "Nonmetals",
      protons: "15",
      electrons: "15",
      neutrons: "16",
      valenceElectrons: "5",
      oxidationNumber: "-3",
      color: "Nonmetals",
    },
    {
      name: "Sulfur",
      symbol: "S",
      groupNumber: "16",
      atomicNumber: "16",
      atomicMass: "32.06",
      groupName: "Nonmetals",
      protons: "16",
      electrons: "16",
      neutrons: "16",
      valenceElectrons: "6",
      oxidationNumber: "-2",
      color: "Nonmetals",
    },
    {
      name: "Chlorine",
      symbol: "Cl",
      groupNumber: "17",
      atomicNumber: "17",
      atomicMass: "35.45",
      groupName: "Halogens",
      protons: "17",
      electrons: "17",
      neutrons: "18",
      valenceElectrons: "7",
      oxidationNumber: "-1",
      color: "Halogens",
    },
    {
      name: "Argon",
      symbol: "Ar",
      groupNumber: "18",
      atomicNumber: "18",
      atomicMass: "39.948",
      groupName: "Noble Gases",
      protons: "18",
      electrons: "18",
      neutrons: "22",
      valenceElectrons: "8",
      oxidationNumber: "0",
      color: "Noble_Gases",
    },
      {
    name: "Potassium",
    symbol: "K",
    groupNumber: "1",
    atomicNumber: "19",
    atomicMass: "39.098",
    groupName: "Alkali Metals",
    protons: "19",
    electrons: "19",
    neutrons: "20",
    valenceElectrons: "1",
    oxidationNumber: "1",
    color: "Alkali_Metals",
  },
  {
    name: "Calcium",
    symbol: "Ca",
    groupNumber: "2",
    atomicNumber: "20",
    atomicMass: "40.08",
    groupName: "Alkaline Earth Metals",
    protons: "20",
    electrons: "20",
    neutrons: "20",
    valenceElectrons: "2",
    oxidationNumber: "2",
    color: "Alkaline_Earth_Metals",
  },
  {
    name: "Scandium",
    symbol: "Sc",
    groupNumber: "3",
    atomicNumber: "21",
    atomicMass: "44.956",
    groupName: "Transition Metals",
    protons: "21",
    electrons: "21",
    neutrons: "24",
    valenceElectrons: "3",
    oxidationNumber: "3",
    color: "Transition_Metals",
  },
  {
    name: "Titanium",
    symbol: "Ti",
    groupNumber: "4",
    atomicNumber: "22",
    atomicMass: "47.867",
    groupName: "Transition Metals",
    protons: "22",
    electrons: "22",
    neutrons: "26",
    valenceElectrons: "4",
    oxidationNumber: "4",
    color: "Transition_Metals",
  },
  {
    name: "Vanadium",
    symbol: "V",
    groupNumber: "5",
    atomicNumber: "23",
    atomicMass: "50.942",
    groupName: "Transition Metals",
    protons: "23",
    electrons: "23",
    neutrons: "28",
    valenceElectrons: "5",
    oxidationNumber: "5",
    color: "Transition_Metals",
  },
  {
    name: "Chromium",
    symbol: "Cr",
    groupNumber: "6",
    atomicNumber: "24",
    atomicMass: "51.996",
    groupName: "Transition Metals",
    protons: "24",
    electrons: "24",
    neutrons: "28",
    valenceElectrons: "6",
    oxidationNumber: "6",
    color: "Transition_Metals",
  },
  {
    name: "Manganese",
    symbol: "Mn",
    groupNumber: "7",
    atomicNumber: "25",
    atomicMass: "54.938",
    groupName: "Transition Metals",
    protons: "25",
    electrons: "25",
    neutrons: "30",
    valenceElectrons: "7",
    oxidationNumber: "7",
    color: "Transition_Metals",
  },
  {
    name: "Iron",
    symbol: "Fe",
    groupNumber: "8",
    atomicNumber: "26",
    atomicMass: "55.845",
    groupName: "Transition Metals",
    protons: "26",
    electrons: "26",
    neutrons: "30",
    valenceElectrons: "8",
    oxidationNumber: "2, 3",
    color: "Transition_Metals",
  },
  {
    name: "Cobalt",
    symbol: "Co",
    groupNumber: "9",
    atomicNumber: "27",
    atomicMass: "58.933",
    groupName: "Transition Metals",
    protons: "27",
    electrons: "27",
    neutrons: "32",
    valenceElectrons: "9",
    oxidationNumber: "2, 3",
    color: "Transition_Metals",
  },
  {
    name: "Nickel",
    symbol: "Ni",
    groupNumber: "10",
    atomicNumber: "28",
    atomicMass: "58.693",
    groupName: "Transition Metals",
    protons: "28",
    electrons: "28",
    neutrons: "31",
    valenceElectrons: "10",
    oxidationNumber: "2, 3",
    color: "Transition_Metals",
  },
  {
    name: "Copper",
    symbol: "Cu",
    groupNumber: "11",
    atomicNumber: "29",
    atomicMass: "63.546",
    groupName: "Transition Metals",
    protons: "29",
    electrons: "29",
    neutrons: "35",
    valenceElectrons: "11",
    oxidationNumber: "1, 2",
    color: "Transition_Metals",
  },
  {
    name: "Zinc",
    symbol: "Zn",
    groupNumber: "12",
    atomicNumber: "30",
    atomicMass: "65.38",
    groupName: "Transition Metals",
    protons: "30",
    electrons: "30",
    neutrons: "35",
    valenceElectrons: "12",
    oxidationNumber: "2",
    color: "Transition_Metals",
  },
  {
    name: "Gallium",
    symbol: "Ga",
    groupNumber: "13",
    atomicNumber: "31",
    atomicMass: "69.723",
    groupName: "Other Metals",
    protons: "31",
    electrons: "31",
    neutrons: "39",
    valenceElectrons: "13",
    oxidationNumber: "3",
    color: "Other_Metals",
  },
  {
    name: "Germanium",
    symbol: "Ge",
    groupNumber: "14",
    atomicNumber: "32",
    atomicMass: "72.630",
    groupName: "Metalloids",
    protons: "32",
    electrons: "32",
    neutrons: "41",
    valenceElectrons: "14",
    oxidationNumber: "4",
    color: "Metalloids",
  },
  {
    name: "Arsenic",
    symbol: "As",
    groupNumber: "15",
    atomicNumber: "33",
    atomicMass: "74.922",
    groupName: "Metalloids",
    protons: "33",
    electrons: "33",
    neutrons: "42",
    valenceElectrons: "15",
    oxidationNumber: "-3, 3, 5",
    color: "Metalloids",
  },
  {
    name: "Selenium",
    symbol: "Se",
    groupNumber: "16",
    atomicNumber: "34",
    atomicMass: "78.971",
    groupName: "Nonmetals",
    protons: "34",
    electrons: "34",
    neutrons: "45",
    valenceElectrons: "16",
    oxidationNumber: "-2, 4, 6",
    color: "Nonmetals",
  },
  {
    name: "Bromine",
    symbol: "Br",
    groupNumber: "17",
    atomicNumber: "35",
    atomicMass: "79.904",
    groupName: "Halogens",
    protons: "35",
    electrons: "35",
    neutrons: "45",
    valenceElectrons: "17",
    oxidationNumber: "-1, 1, 5, 7",
    color: "Halogens",
  },
  {
    name: "Krypton",
    symbol: "Kr",
    groupNumber: "18",
    atomicNumber: "36",
    atomicMass: "83.798",
    groupName: "Noble Gases",
    protons: "36",
    electrons: "36",
    neutrons: "48",
    valenceElectrons: "18",
    oxidationNumber: "0",
    color: "Noble_Gases",
  },
  {
    name: "Rubidium",
    symbol: "Rb",
    groupNumber: "1",
    atomicNumber: "37",
    atomicMass: "85.468",
    groupName: "Alkali Metals",
    protons: "37",
    electrons: "37",
    neutrons: "48",
    valenceElectrons: "1",
    oxidationNumber: "1",
    color: "Alkali_Metals",
  },
  {
    name: "Strontium",
    symbol: "Sr",
    groupNumber: "2",
    atomicNumber: "38",
    atomicMass: "87.62",
    groupName: "Alkaline Earth Metals",
    protons: "38",
    electrons: "38",
    neutrons: "50",
    valenceElectrons: "2",
    oxidationNumber: "2",
    color: "Alkaline_Earth_Metals",
  },
  {
    name: "Yttrium",
    symbol: "Y",
    groupNumber: "3",
    atomicNumber: "39",
    atomicMass: "88.906",
    groupName: "Transition Metals",
    protons: "39",
    electrons: "39",
    neutrons: "50",
    valenceElectrons: "3",
    oxidationNumber: "3",
    color: "Transition_Metals",
  },
  {
    name: "Zirconium",
    symbol: "Zr",
    groupNumber: "4",
    atomicNumber: "40",
    atomicMass: "91.224",
    groupName: "Transition Metals",
    protons: "40",
    electrons: "40",
    neutrons: "51",
    valenceElectrons: "4",
    oxidationNumber: "4",
    color: "Transition_Metals",
  },
  {
    name: "Niobium",
    symbol: "Nb",
    groupNumber: "5",
    atomicNumber: "41",
    atomicMass: "92.906",
    groupName: "Transition Metals",
    protons: "41",
    electrons: "41",
    neutrons: "52",
    valenceElectrons: "5",
    oxidationNumber: "5",
    color: "Transition_Metals",
  },
  {
    name: "Molybdenum",
    symbol: "Mo",
    groupNumber: "6",
    atomicNumber: "42",
    atomicMass: "95.95",
    groupName: "Transition Metals",
    protons: "42",
    electrons: "42",
    neutrons: "54",
    valenceElectrons: "6",
    oxidationNumber: "6",
    color: "Transition_Metals",
  },
  {
    name: "Technetium",
    symbol: "Tc",
    groupNumber: "7",
    atomicNumber: "43",
    atomicMass: "98",
    groupName: "Transition Metals",
    protons: "43",
    electrons: "43",
    neutrons: "55",
    valenceElectrons: "7",
    oxidationNumber: "7",
    color: "Transition_Metals",
  },
  {
    name: "Ruthenium",
    symbol: "Ru",
    groupNumber: "8",
    atomicNumber: "44",
    atomicMass: "101.1",
    groupName: "Transition Metals",
    protons: "44",
    electrons: "44",
    neutrons: "57",
    valenceElectrons: "8",
    oxidationNumber: "3, 4, 8",
    color: "Transition_Metals",
  },
  {
    name: "Rhodium",
    symbol: "Rh",
    groupNumber: "9",
    atomicNumber: "45",
    atomicMass: "102.9",
    groupName: "Transition Metals",
    protons: "45",
    electrons: "45",
    neutrons: "58",
    valenceElectrons: "9",
    oxidationNumber: "3",
    color: "Transition_Metals",
  },
  {
    name: "Palladium",
    symbol: "Pd",
    groupNumber: "10",
    atomicNumber: "46",
    atomicMass: "106.4",
    groupName: "Transition Metals",
    protons: "46",
    electrons: "46",
    neutrons: "60",
    valenceElectrons: "10",
    oxidationNumber: "2, 4",
    color: "Transition_Metals",
  },
  {
    name: "Silver",
    symbol: "Ag",
    groupNumber: "11",
    atomicNumber: "47",
    atomicMass: "107.9",
    groupName: "Transition Metals",
    protons: "47",
    electrons: "47",
    neutrons: "61",
    valenceElectrons: "11",
    oxidationNumber: "1",
    color: "Transition_Metals",
  },
      {
    name: "Molybdenum",
    symbol: "Mo",
    groupNumber: "6",
    atomicNumber: "42",
    atomicMass: "95.95",
    groupName: "Transition Metals",
    protons: "42",
    electrons: "42",
    neutrons: "54",
    valenceElectrons: "6",
    oxidationNumber: "4",
    color: "Transition_Metals",
  },
  {
    name: "Technetium",
    symbol: "Tc",
    groupNumber: "7",
    atomicNumber: "43",
    atomicMass: "(98)",
    groupName: "Transition Metals",
    protons: "43",
    electrons: "43",
    neutrons: "(55)",
    valenceElectrons: "7",
    oxidationNumber: "7",
    color: "Transition_Metals",
  },
  {
    name: "Ruthenium",
    symbol: "Ru",
    groupNumber: "8",
    atomicNumber: "44",
    atomicMass: "101.1",
    groupName: "Transition Metals",
    protons: "44",
    electrons: "44",
    neutrons: "57",
    valenceElectrons: "8",
    oxidationNumber: "3",
    color: "Transition_Metals",
  },
  {
    name: "Rhodium",
    symbol: "Rh",
    groupNumber: "9",
    atomicNumber: "45",
    atomicMass: "102.9",
    groupName: "Transition Metals",
    protons: "45",
    electrons: "45",
    neutrons: "58",
    valenceElectrons: "9",
    oxidationNumber: "3",
    color: "Transition_Metals",
  },
  {
    name: "Palladium",
    symbol: "Pd",
    groupNumber: "10",
    atomicNumber: "46",
    atomicMass: "106.4",
    groupName: "Transition Metals",
    protons: "46",
    electrons: "46",
    neutrons: "60",
    valenceElectrons: "10",
    oxidationNumber: "2",
    color: "Transition_Metals",
  },
  {
    name: "Silver",
    symbol: "Ag",
    groupNumber: "11",
    atomicNumber: "47",
    atomicMass: "107.9",
    groupName: "Transition Metals",
    protons: "47",
    electrons: "47",
    neutrons: "61",
    valenceElectrons: "11",
    oxidationNumber: "1",
    color: "Transition_Metals",
  },
  {
    name: "Cadmium",
    symbol: "Cd",
    groupNumber: "12",
    atomicNumber: "48",
    atomicMass: "112.4",
    groupName: "Transition Metals",
    protons: "48",
    electrons: "48",
    neutrons: "64",
    valenceElectrons: "12",
    oxidationNumber: "2",
    color: "Transition_Metals",
  },
  {
    name: "Indium",
    symbol: "In",
    groupNumber: "13",
    atomicNumber: "49",
    atomicMass: "114.8",
    groupName: "Other Metals",
    protons: "49",
    electrons: "49",
    neutrons: "65",
    valenceElectrons: "13",
    oxidationNumber: "3",
    color: "Other_Metals",
  },
  {
    name: "Tin",
    symbol: "Sn",
    groupNumber: "14",
    atomicNumber: "50",
    atomicMass: "118.7",
    groupName: "Other Metals",
    protons: "50",
    electrons: "50",
    neutrons: "70",
    valenceElectrons: "14",
    oxidationNumber: "4",
    color: "Other_Metals",
  },
  {
    name: "Antimony",
    symbol: "Sb",
    groupNumber: "15",
    atomicNumber: "51",
    atomicMass: "121.8",
    groupName: "Metalloids",
    protons: "51",
    electrons: "51",
    neutrons: "71",
    valenceElectrons: "15",
    oxidationNumber: "5",
    color: "Metalloids",
  },
  {
    name: "Tellurium",
    symbol: "Te",
    groupNumber: "16",
    atomicNumber: "52",
    atomicMass: "127.6",
    groupName: "Metalloids",
    protons: "52",
    electrons: "52",
    neutrons: "76",
    valenceElectrons: "16",
    oxidationNumber: "-2",
    color: "Metalloids",
  },
  {
    name: "Iodine",
    symbol: "I",
    groupNumber: "17",
    atomicNumber: "53",
    atomicMass: "126.9",
    groupName: "Halogens",
    protons: "53",
    electrons: "53",
    neutrons: "74",
    valenceElectrons: "17",
    oxidationNumber: "-1",
    color: "Halogens",
  },
  {
    name: "Xenon",
    symbol: "Xe",
    groupNumber: "18",
    atomicNumber: "54",
    atomicMass: "131.3",
    groupName: "Noble Gases",
    protons: "54",
    electrons: "54",
    neutrons: "77",
    valenceElectrons: "18",
    oxidationNumber: "0",
    color: "Noble_Gases",
  },
  {
    name: "Cesium",
    symbol: "Cs",
    groupNumber: "1",
    atomicNumber: "55",
    atomicMass: "132.9",
    groupName: "Alkali Metals",
    protons: "55",
    electrons: "55",
    neutrons: "78",
    valenceElectrons: "1",
    oxidationNumber: "1",
    color: "Alkali_Metals",
  },
  {
    name: "Barium",
    symbol: "Ba",
    groupNumber: "2",
    atomicNumber: "56",
    atomicMass: "137.3",
    groupName: "Alkaline Earth Metals",
    protons: "56",
    electrons: "56",
    neutrons: "81",
    valenceElectrons: "2",
    oxidationNumber: "2",
    color: "Alkaline_Earth_Metals",
  },
  {
    name: "Lanthanum",
    symbol: "La",
    groupNumber: "N/A",
    atomicNumber: "57",
    atomicMass: "138.9",
    groupName: "Lanthanides",
    protons: "57",
    electrons: "57",
    neutrons: "82",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
  {
    name: "Cerium",
    symbol: "Ce",
    groupNumber: "N/A",
    atomicNumber: "58",
    atomicMass: "140.1",
    groupName: "Lanthanides",
    protons: "58",
    electrons: "58",
    neutrons: "82",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
  {
    name: "Praseodymium",
    symbol: "Pr",
    groupNumber: "N/A",
    atomicNumber: "59",
    atomicMass: "140.9",
    groupName: "Lanthanides",
    protons: "59",
    electrons: "59",
    neutrons: "82",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
  {
    name: "Neodymium",
    symbol: "Nd",
    groupNumber: "N/A",
    atomicNumber: "60",
    atomicMass: "144.2",
    groupName: "Lanthanides",
    protons: "60",
    electrons: "60",
    neutrons: "84",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
  {
    name: "Promethium",
    symbol: "Pm",
    groupNumber: "N/A",
    atomicNumber: "61",
    atomicMass: "(145)",
    groupName: "Lanthanides",
    protons: "61",
    electrons: "61",
    neutrons: "(84)",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
  {
    name: "Samarium",
    symbol: "Sm",
    groupNumber: "N/A",
    atomicNumber: "62",
    atomicMass: "150.4",
    groupName: "Lanthanides",
    protons: "62",
    electrons: "62",
    neutrons: "88",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
  {
    name: "Europium",
    symbol: "Eu",
    groupNumber: "N/A",
    atomicNumber: "63",
    atomicMass: "152.0",
    groupName: "Lanthanides",
    protons: "63",
    electrons: "63",
    neutrons: "89",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
  {
    name: "Gadolinium",
    symbol: "Gd",
    groupNumber: "N/A",
    atomicNumber: "64",
    atomicMass: "157.3",
    groupName: "Lanthanides",
    protons: "64",
    electrons: "64",
    neutrons: "93",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
      {
          name: "Terbium",
          symbol: "Tb",
          groupNumber: "N/A",
          atomicNumber: "65",
          atomicMass: "158.9",
          groupName: "Lanthanides",
          protons: "65",
          electrons: "65",
          neutrons: "94",
          valenceElectrons: "N/A",
          oxidationNumber: "3",
          color: "Lanthanides"
      },
      {
    name: "Dysprosium",
    symbol: "Dy",
    groupNumber: "N/A",
    atomicNumber: "66",
    atomicMass: "162.5",
    groupName: "Lanthanides",
    protons: "66",
    electrons: "66",
    neutrons: "96",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
  {
    name: "Holmium",
    symbol: "Ho",
    groupNumber: "N/A",
    atomicNumber: "67",
    atomicMass: "164.9",
    groupName: "Lanthanides",
    protons: "67",
    electrons: "67",
    neutrons: "98",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
  {
    name: "Erbium",
    symbol: "Er",
    groupNumber: "N/A",
    atomicNumber: "68",
    atomicMass: "167.3",
    groupName: "Lanthanides",
    protons: "68",
    electrons: "68",
    neutrons: "100",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
  {
    name: "Thulium",
    symbol: "Tm",
    groupNumber: "N/A",
    atomicNumber: "69",
    atomicMass: "168.9",
    groupName: "Lanthanides",
    protons: "69",
    electrons: "69",
    neutrons: "101",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
  {
    name: "Ytterbium",
    symbol: "Yb",
    groupNumber: "N/A",
    atomicNumber: "70",
    atomicMass: "173.0",
    groupName: "Lanthanides",
    protons: "70",
    electrons: "70",
    neutrons: "103",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
  {
    name: "Lutetium",
    symbol: "Lu",
    groupNumber: "3",
    atomicNumber: "71",
    atomicMass: "175.0",
    groupName: "Lanthanides",
    protons: "71",
    electrons: "71",
    neutrons: "104",
    valenceElectrons: "3",
    oxidationNumber: "3",
    color: "Lanthanides",
  },
  {
    name: "Hafnium",
    symbol: "Hf",
    groupNumber: "4",
    atomicNumber: "72",
    atomicMass: "178.5",
    groupName: "Transition Metals",
    protons: "72",
    electrons: "72",
    neutrons: "106",
    valenceElectrons: "4",
    oxidationNumber: "4",
    color: "Transition_Metals",
  },
  {
    name: "Tantalum",
    symbol: "Ta",
    groupNumber: "5",
    atomicNumber: "73",
    atomicMass: "180.9",
    groupName: "Transition Metals",
    protons: "73",
    electrons: "73",
    neutrons: "108",
    valenceElectrons: "5",
    oxidationNumber: "5",
    color: "Transition_Metals",
  },
  {
    name: "Tungsten",
    symbol: "W",
    groupNumber: "6",
    atomicNumber: "74",
    atomicMass: "183.8",
    groupName: "Transition Metals",
    protons: "74",
    electrons: "74",
    neutrons: "110",
    valenceElectrons: "6",
    oxidationNumber: "6",
    color: "Transition_Metals",
  },
  {
    name: "Rhenium",
    symbol: "Re",
    groupNumber: "7",
    atomicNumber: "75",
    atomicMass: "186.2",
    groupName: "Transition Metals",
    protons: "75",
    electrons: "75",
    neutrons: "111",
    valenceElectrons: "7",
    oxidationNumber: "7",
    color: "Transition_Metals",
  },
  {
    name: "Osmium",
    symbol: "Os",
    groupNumber: "8",
    atomicNumber: "76",
    atomicMass: "190.2",
    groupName: "Transition Metals",
    protons: "76",
    electrons: "76",
    neutrons: "114",
    valenceElectrons: "8",
    oxidationNumber: "4",
    color: "Transition_Metals",
  },
  {
    name: "Iridium",
    symbol: "Ir",
    groupNumber: "9",
    atomicNumber: "77",
    atomicMass: "192.2",
    groupName: "Transition Metals",
    protons: "77",
    electrons: "77",
    neutrons: "115",
    valenceElectrons: "9",
    oxidationNumber: "4",
    color: "Transition_Metals",
  },
  {
    name: "Platinum",
    symbol: "Pt",
    groupNumber: "10",
    atomicNumber: "78",
    atomicMass: "195.1",
    groupName: "Transition Metals",
    protons: "78",
    electrons: "78",
    neutrons: "117",
    valenceElectrons: "10",
    oxidationNumber: "2",
    color: "Transition_Metals",
  },
  {
    name: "Gold",
    symbol: "Au",
    groupNumber: "11",
    atomicNumber: "79",
    atomicMass: "197.0",
    groupName: "Transition Metals",
    protons: "79",
    electrons: "79",
    neutrons: "118",
    valenceElectrons: "11",
    oxidationNumber: "3",
    color: "Transition_Metals",
  },
  {
    name: "Mercury",
    symbol: "Hg",
    groupNumber: "12",
    atomicNumber: "80",
    atomicMass: "200.6",
    groupName: "Transition Metals",
    protons: "80",
    electrons: "80",
    neutrons: "121",
    valenceElectrons: "12",
    oxidationNumber: "2",
    color: "Transition_Metals",
  },
  {
    name: "Thallium",
    symbol: "Tl",
    groupNumber: "13",
    atomicNumber: "81",
    atomicMass: "204.4",
    groupName: "Other Metals",
    protons: "81",
    electrons: "81",
    neutrons: "123",
    valenceElectrons: "13",
    oxidationNumber: "1",
    color: "Other_Metals",
  },
  {
    name: "Lead",
    symbol: "Pb",
    groupNumber: "14",
    atomicNumber: "82",
    atomicMass: "207.2",
    groupName: "Other Metals",
    protons: "82",
    electrons: "82",
    neutrons: "125",
    valenceElectrons: "14",
    oxidationNumber: "2",
    color: "Other_Metals",
  },
  {
    name: "Bismuth",
    symbol: "Bi",
    groupNumber: "15",
    atomicNumber: "83",
    atomicMass: "208.9",
    groupName: "Other Metals",
    protons: "83",
    electrons: "83",
    neutrons: "126",
    valenceElectrons: "15",
    oxidationNumber: "3",
    color: "Other_Metals",
  },
  {
    name: "Polonium",
    symbol: "Po",
    groupNumber: "16",
    atomicNumber: "84",
    atomicMass: "(209)",
    groupName: "Metalloids",
    protons: "84",
    electrons: "84",
    neutrons: "(126)",
    valenceElectrons: "16",
    oxidationNumber: "-2",
    color: "Metalloids",
  },
  {
    name: "Astatine",
    symbol: "At",
    groupNumber: "17",
    atomicNumber: "85",
    atomicMass: "(210)",
    groupName: "Halogens",
    protons: "85",
    electrons: "85",
    neutrons: "(125)",
    valenceElectrons: "17",
    oxidationNumber: "-1",
    color: "Halogens",
  },
  {
    name: "Radon",
    symbol: "Rn",
    groupNumber: "18",
    atomicNumber: "86",
    atomicMass: "(222)",
    groupName: "Noble Gases",
    protons: "86",
    electrons: "86",
    neutrons: "(136)",
    valenceElectrons: "18",
    oxidationNumber: "0",
    color: "Noble_Gases",
  },
  {
    name: "Francium",
    symbol: "Fr",
    groupNumber: "1",
    atomicNumber: "87",
    atomicMass: "(223)",
    groupName: "Alkali Metals",
    protons: "87",
    electrons: "87",
    neutrons: "(136)",
    valenceElectrons: "1",
    oxidationNumber: "1",
    color: "Alkali_Metals",
  },
  {
    name: "Radium",
    symbol: "Ra",
    groupNumber: "2",
    atomicNumber: "88",
    atomicMass: "(226)",
    groupName: "Alkaline Earth Metals",
    protons: "88",
    electrons: "88",
    neutrons: "(138)",
    valenceElectrons: "2",
    oxidationNumber: "2",
    color: "Alkaline_Earth_Metals",
  },
  {
    name: "Actinium",
    symbol: "Ac",
    groupNumber: "N/A",
    atomicNumber: "89",
    atomicMass: "(227)",
    groupName: "Actinides",
    protons: "89",
    electrons: "89",
    neutrons: "(138)",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Actinides",
  },
  {
    name: "Thorium",
    symbol: "Th",
    groupNumber: "N/A",
    atomicNumber: "90",
    atomicMass: "232.0",
    groupName: "Actinides",
    protons: "90",
    electrons: "90",
    neutrons: "142",
    valenceElectrons: "N/A",
    oxidationNumber: "4",
    color: "Actinides",
  },
  {
    name: "Protactinium",
    symbol: "Pa",
    groupNumber: "N/A",
    atomicNumber: "91",
    atomicMass: "(231)",
    groupName: "Actinides",
    protons: "91",
    electrons: "91",
    neutrons: "(140)",
    valenceElectrons: "N/A",
    oxidationNumber: "5",
    color: "Actinides",
  },
  {
    name: "Uranium",
    symbol: "U",
    groupNumber: "N/A",
    atomicNumber: "92",
    atomicMass: "238.0",
    groupName: "Actinides",
    protons: "92",
    electrons: "92",
    neutrons: "146",
    valenceElectrons: "N/A",
    oxidationNumber: "6",
    color: "Actinides",
  },
  {
    name: "Neptunium",
    symbol: "Np",
    groupNumber: "N/A",
    atomicNumber: "93",
    atomicMass: "(237)",
    groupName: "Actinides",
    protons: "93",
    electrons: "93",
    neutrons: "(144)",
    valenceElectrons: "N/A",
    oxidationNumber: "5",
    color: "Actinides",
  },
  {
    name: "Plutonium",
    symbol: "Pu",
    groupNumber: "N/A",
    atomicNumber: "94",
    atomicMass: "(244)",
    groupName: "Actinides",
    protons: "94",
    electrons: "94",
    neutrons: "(150)",
    valenceElectrons: "N/A",
    oxidationNumber: "4",
    color: "Actinides",
  },
  {
    name: "Americium",
    symbol: "Am",
    groupNumber: "N/A",
    atomicNumber: "95",
    atomicMass: "(243)",
    groupName: "Actinides",
    protons: "95",
    electrons: "95",
    neutrons: "(148)",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Actinides",
  },
  {
    name: "Curium",
    symbol: "Cm",
    groupNumber: "N/A",
    atomicNumber: "96",
    atomicMass: "(247)",
    groupName: "Actinides",
    protons: "96",
    electrons: "96",
    neutrons: "(151)",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Actinides",
  },
  {
    name: "Berkelium",
    symbol: "Bk",
    groupNumber: "N/A",
    atomicNumber: "97",
    atomicMass: "(247)",
    groupName: "Actinides",
    protons: "97",
    electrons: "97",
    neutrons: "(150)",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Actinides",
  },
  {
    name: "Californium",
    symbol: "Cf",
    groupNumber: "N/A",
    atomicNumber: "98",
    atomicMass: "(251)",
    groupName: "Actinides",
    protons: "98",
    electrons: "98",
    neutrons: "(153)",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Actinides",
  },
  {
    name: "Einsteinium",
    symbol: "Es",
    groupNumber: "N/A",
    atomicNumber: "99",
    atomicMass: "(252)",
    groupName: "Actinides",
    protons: "99",
    electrons: "99",
    neutrons: "(153)",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Actinides",
  },
  {
    name: "Fermium",
    symbol: "Fm",
    groupNumber: "N/A",
    atomicNumber: "100",
    atomicMass: "(257)",
    groupName: "Actinides",
    protons: "100",
    electrons: "100",
    neutrons: "(157)",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Actinides",
  },
  {
    name: "Mendelevium",
    symbol: "Md",
    groupNumber: "N/A",
    atomicNumber: "101",
    atomicMass: "(258)",
    groupName: "Actinides",
    protons: "101",
    electrons: "101",
    neutrons: "(157)",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Actinides",
  },
  {
    name: "Nobelium",
    symbol: "No",
    groupNumber: "N/A",
    atomicNumber: "102",
    atomicMass: "(259)",
    groupName: "Actinides",
    protons: "102",
    electrons: "102",
    neutrons: "(157)",
    valenceElectrons: "N/A",
    oxidationNumber: "2",
    color: "Actinides",
  },
  {
    name: "Lawrencium",
    symbol: "Lr",
    groupNumber: "N/A",
    atomicNumber: "103",
    atomicMass: "(266)",
    groupName: "Actinides",
    protons: "103",
    electrons: "103",
    neutrons: "(163)",
    valenceElectrons: "N/A",
    oxidationNumber: "3",
    color: "Actinides",
  },
  {
    name: "Rutherfordium",
    symbol: "Rf",
    groupNumber: "4",
    atomicNumber: "104",
    atomicMass: "(267)",
    groupName: "Transition Metals",
    protons: "104",
    electrons: "104",
    neutrons: "(163)",
    valenceElectrons: "4",
    oxidationNumber: "4",
    color: "Transition_Metals",
  },
  {
    name: "Dubnium",
    symbol: "Db",
    groupNumber: "5",
    atomicNumber: "105",
    atomicMass: "(270)",
    groupName: "Transition Metals",
    protons: "105",
    electrons: "105",
    neutrons: "(163)",
    valenceElectrons: "5",
    oxidationNumber: "5",
    color: "Transition_Metals",
  },
  {
    name: "Seaborgium",
    symbol: "Sg",
    groupNumber: "6",
    atomicNumber: "106",
    atomicMass: "(269)",
    groupName: "Transition Metals",
    protons: "106",
    electrons: "106",
    neutrons: "(163)",
    valenceElectrons: "6",
    oxidationNumber: "6",
    color: "Transition_Metals",
  },
  {
    name: "Bohrium",
    symbol: "Bh",
    groupNumber: "7",
    atomicNumber: "107",
    atomicMass: "(270)",
    groupName: "Transition Metals",
    protons: "107",
    electrons: "107",
    neutrons: "(163)",
    valenceElectrons: "7",
    oxidationNumber: "7",
    color: "Transition_Metals",
  },
  {
    name: "Hassium",
    symbol: "Hs",
    groupNumber: "8",
    atomicNumber: "108",
    atomicMass: "(277)",
    groupName: "Transition Metals",
    protons: "108",
    electrons: "108",
    neutrons: "(169)",
    valenceElectrons: "8",
    oxidationNumber: "8",
    color: "Transition_Metals",
  },
  {
    name: "Meitnerium",
    symbol: "Mt",
    groupNumber: "9",
    atomicNumber: "109",
    atomicMass: "(278)",
    groupName: "Transition Metals",
    protons: "109",
    electrons: "109",
    neutrons: "(169)",
    valenceElectrons: "9",
    oxidationNumber: "9",
    color: "Transition_Metals",
  },
  {
    name: "Darmstadtium",
    symbol: "Ds",
    groupNumber: "10",
    atomicNumber: "110",
    atomicMass: "(281)",
    groupName: "Transition Metals",
    protons: "110",
    electrons: "110",
    neutrons: "(171)",
    valenceElectrons: "10",
    oxidationNumber: "10",
    color: "Transition_Metals",
  },
  {
    name: "Roentgenium",
    symbol: "Rg",
    groupNumber: "11",
    atomicNumber: "111",
    atomicMass: "(282)",
    groupName: "Transition Metals",
    protons: "111",
    electrons: "111",
    neutrons: "(171)",
    valenceElectrons: "11",
    oxidationNumber: "11",
    color: "Transition_Metals",
  },
  {
    name: "Copernicium",
    symbol: "Cn",
    groupNumber: "12",
    atomicNumber: "112",
    atomicMass: "(285)",
    groupName: "Transition Metals",
    protons: "112",
    electrons: "112",
    neutrons: "(173)",
    valenceElectrons: "12",
    oxidationNumber: "12",
    color: "Transition_Metals",
  },
  {
    name: "Nihonium",
    symbol: "Nh",
    groupNumber: "13",
    atomicNumber: "113",
    atomicMass: "(286)",
    groupName: "Other Metals",
    protons: "113",
    electrons: "113",
    neutrons: "(173)",
    valenceElectrons: "13",
    oxidationNumber: "13",
    color: "Other_Metals",
  },
  {
    name: "Flerovium",
    symbol: "Fl",
    groupNumber: "14",
    atomicNumber: "114",
    atomicMass: "(289)",
    groupName: "Other Metals",
    protons: "114",
    electrons: "114",
    neutrons: "(175)",
    valenceElectrons: "14",
    oxidationNumber: "14",
    color: "Other_Metals",
  },
  {
    name: "Moscovium",
    symbol: "Mc",
    groupNumber: "15",
    atomicNumber: "115",
    atomicMass: "(290)",
    groupName: "Other Metals",
    protons: "115",
    electrons: "115",
    neutrons: "(175)",
    valenceElectrons: "15",
    oxidationNumber: "15",
    color: "Other_Metals",
  },
  {
    name: "Livermorium",
    symbol: "Lv",
    groupNumber: "16",
    atomicNumber: "116",
    atomicMass: "(293)",
    groupName: "Other Metals",
    protons: "116",
    electrons: "116",
    neutrons: "(177)",
    valenceElectrons: "16",
    oxidationNumber: "16",
    color: "Other_Metals",
  },
  {
    name: "Tennessine",
    symbol: "Ts",
    groupNumber: "17",
    atomicNumber: "117",
    atomicMass: "(294)",
    groupName: "Halogens",
    protons: "117",
    electrons: "117",
    neutrons: "(177)",
    valenceElectrons: "17",
    oxidationNumber: "-1",
    color: "Halogens",
  },
  {
    name: "Oganesson",
    symbol: "Og",
    groupNumber: "18",
    atomicNumber: "118",
    atomicMass: "(294)",
    groupName: "Noble Gases",
    protons: "118",
    electrons: "118",
    neutrons: "(176)",
    valenceElectrons: "18",
    oxidationNumber: "0",
    color: "Noble_Gases",
  },
  ]
  
  const categories = [...new Set(product.map((item) => { return item }))]
  
  document.getElementById('searchBar').addEventListener('keyup', (e) => {
      const searchData = e.target.value.toLowerCase();
      const filteredData = categories.filter((item) => {
          return(
              item.name.toLocaleLowerCase().includes(searchData) || 
              item.symbol.toLocaleLowerCase().includes(searchData) || 
              item.groupName.toLocaleLowerCase().includes(searchData)  || 
              item.atomicNumber.toLocaleLowerCase().includes(searchData) || 
              item.atomicMass.toLocaleLowerCase().includes(searchData) || 
              item.protons.toLocaleLowerCase().includes(searchData) || 
              item.neutrons.toLocaleLowerCase().includes(searchData) || 
              item.electrons.toLocaleLowerCase().includes(searchData) || 
              item.valenceElectrons.toLocaleLowerCase().includes(searchData) || 
              item.oxidationNumber.toLocaleLowerCase().includes(searchData) || 
              item.groupNumber.toLocaleLowerCase().includes(searchData)
          );
      });
      displayItem(filteredData)
  });
  
  const displayItem = (items) => {
      document.getElementById('root').innerHTML = items.map((item) => {
          var { name, symbol, atomicNumber, color , atomicMass, groupName, protons, neutrons, electrons, valenceElectrons, oxidationNumber, groupNumber} = item;
          return (
              `<div class='${color}'>
              <div class="row">
                <div class="column"><p id="number">#${atomicNumber}</p></div>
                <div class="column"><p id="mass">${atomicMass}</p></div>
              </div>
                  <div class="main">
                    <h3 id="symbol">${symbol}</h3>
                    <h3 id="name">${name}</h3>
                    <p id="group">${groupName}</p>
  
                      <hr id="thing">
  
                    <h4>Other:</h4>
                    <div class="row">
                      <div class="column"><p id="Other">Protons - ${protons}</p></div>
                      <div class="column"><p id="Other">Neutrons - ${neutrons}</p></div>
                  </div>
                  <div class="row1">
                      <div class="column1"><p id="Other">Electrons - ${electrons}</p></div>
                      <div class="column1"><p id="Other">Valence Electrons - ${valenceElectrons}</p></div>
                  </div>
                  <div class="row2">
                      <div class="column2"><p id="Other">Group Number - #${groupNumber}</p></div>
                      <div class="column2"><p id="Other">Oxidation Number - ${oxidationNumber}</p></div>
                  </div>
                  </div>
                </div>`
                )
              }).join('')
          };
          displayItem(categories);